apiVersion: primaza.io/v1alpha1
kind: RegisteredService
metadata:
  name: sqs-queue-writer
spec:
  serviceClassIdentity:
  - name: type
    value: sqs
  - name: scope
    value: demo-app
  - name: provider
    value: aws
  - name: role
    value: writer
  serviceEndpointDefinition:
  - name: url
    value: https://my-app-for-appns-service.dev
  - name: password
    value: SomeoneThinksImAPassword

