apiVersion: sqs.services.k8s.aws/v1alpha1
kind: Queue
metadata:
  name: my-queue
spec:
  queueName: myqueue
  delaySeconds: "0"
  tags:
    key1: val1
---
### TODO: This role is a workaround for having metadata on service
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: primaza-mon-ack-sqs
rules:
- apiGroups:
  - sqs.services.k8s.aws
  resources:
  - queues
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: primaza-mon-ack-sqs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: primaza-mon-ack-sqs
subjects:
- kind: ServiceAccount
  name: primaza-primaza-mytenant-self-demo
  namespace: kube-system
