apiVersion: primaza.io/v1alpha1
kind: ServiceClaim
metadata:
  name: sqs-orders-event
  namespace: primaza-system
spec:
  serviceClassIdentity:
  - name: type
    value: sqs
  - name: scope
    value: demo-app
  - name: provider
    value: aws
  - name: role
    value: writer
  serviceEndpointDefinitionKeys:
  - url
  - password
  environmentTag: stage
  application:
    kind: Deployment
    apiVersion: apps/v1
    selector:
      matchLabels:
        app: orders-events-consumer
