apiVersion: primaza.io/v1alpha1
kind: ServiceClaim
metadata:
  name: orders-dynamo
  namespace: primaza-system
spec:
  serviceClassIdentity:
  - name: type
    value: dynamo
  - name: scope
    value: demo-app
  - name: provider
    value: aws
  serviceEndpointDefinitionKeys:
  - url
  - password
  environmentTag: stage
  application:
    kind: Deployment
    apiVersion: apps/v1
    selector:
      matchLabels:
        app: orders
