apiVersion: primaza.io/v1alpha1
kind: ServiceClaim
metadata:
  name: sc-test
  namespace: primaza-system
spec:
  serviceClassIdentity:
  - name: type
    value: dummy
  - name: scope
    value: claim-for-appns
  serviceEndpointDefinitionKeys:
  - url
  - password
  environmentTag: stage
  application:
    kind: Deployment
    apiVersion: apps/v1
    selector:
      matchLabels:
        app: myapp

